name: resqalerts
description: "Emergency notification app for community response"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  cloud_firestore: ^4.17.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
